### ISSUE TITLE
Couldn't decode Elm 0.19 package elm.json

### ISSUE THREAD

**Issue by avh4** [stoeffel/elmi-to-json#14]
Run elmi-to-json in a folder with the following `elm.json` file:

```json
{
    "type": "package",
    "name": "avh4/elm-fifo",
    "summary": "First in, first out (FIFO) queue",
    "license": "MIT",
    "version": "1.0.4",
    "exposed-modules": [
        "Fifo"
    ],
    "elm-version": "0.19.0 <= v < 0.20.0",
    "dependencies": {
        "elm/core": "1.0.0 <= v < 2.0.0"
    },
    "test-dependencies": {}
}
```

produces the following error: 

```
elmi-to-json failed for:
all

Couldn't decode /Users/avh4/workspace/elmi-to-json/tmp_test_workspace/elm.json
```

**Comment by stoeffel** [comment]
Oh, I think it's because of two different problems.
`source-directories` is optional now and `elm-version` can be a range.

How about adding a `--elm-version` argument and default to the folder with the highest version number?
https://github.com/stoeffel/elmi-to-json/blob/53f9a12223e74b1890c290fb197d582d39201037/src/Elmi.hs#L73

**Comment by stoeffel** [comment]
IRL: hard code version, since we will release a new version of elmi-to-json whenever we have a new elm release.
